@echo off
rem VR boot knobs for vr438 (current KEEP). Applied before GevrRomStarter runs goldeneye.exe.

set GETV_FPS=90
set GETV_MSGSCALE=434
set GETV_SRCFBO=1
set GETV_SUPERSAMPLE=3

set GETV_STEREO=1
set GETV_STEREO_MODE=1
set GETV_STEREO_OFFSET=32
set GETV_STEREO_PROBE=60
set GETV_STEREO_VIEWRESTORE=1
set GETV_STEREO_PAIRGUARD=0
set GETV_STEREO_REBUILD=1
set GETV_STEREO_REBUILD_REPORT=1
set GETV_STEREO_REBUILD_VIEWER=1

set GE_VR_XR=1
